import ITableHead from "@/definitions/ITableHead";
import { Request, Response, RequestHandler, query } from "express";
import { Pool } from "pg";
import { sqlUtils } from "../db";

export default function getTableHeadFunction(): RequestHandler {
  async function getTableHead(req: Request, res: Response): Promise<void> {
    try {
      // const query_result_tables = await sqlUtils.getSchema();
      // let temp_table_heads: Record<string, Promise<ITableHead>> = {};

      // for (const row of query_result_tables) {
      //   const complete_name = `${row.table_schema}.${row.table_name}`;
      //   if (!temp_table_heads[complete_name]) {
      //     console.log(row.table_name, row.table_schema);
      //     temp_table_heads[complete_name] = sqlUtils.getTableHead(
      //       row.table_name,
      //       row.table_schema
      //     );
      //   }
      // }
      // const values = await Promise.all(Object.values(temp_table_heads));
      // const keys = Object.keys(temp_table_heads);
      // const result: Record<string, ITableHead> = {};
      // for (const index in keys) {
      //   result[keys[index]] = values[index];
      // }
      // console.log(result)
      let result: Record<string, ITableHead> = {
        "public.nation_region_denormalized": {
          attributes: [
            "n_nationkey",
            "n_name",
            "n_regionkey",
            "n_comment",
            "r_regionkey",
            "r_name",
            "r_comment",
          ],
          rows: [
            {
              n_nationkey: 6,
              n_name: "FRANCE",
              n_regionkey: 3,
              n_comment: "refully final requests. regular, ironi",
              r_regionkey: 3,
              r_name: "EUROPE",
              r_comment: "ly final courts cajole furiously final excuse",
            },
            {
              n_nationkey: 18,
              n_name: "CHINA",
              n_regionkey: 2,
              n_comment:
                "c dependencies. furiously express notornis sleep slyly regular accounts. ideas sleep. depos",
              r_regionkey: 2,
              r_name: "ASIA",
              r_comment: "ges. thinly even pinto beans ca",
            },
            {
              n_nationkey: 21,
              n_name: "VIETNAM                  ",
              n_regionkey: 2,
              n_comment: "hely enticingly express accounts. even, final ",
              r_regionkey: 2,
              r_name: "ASIA                     ",
              r_comment: "ges. thinly even pinto beans ca",
            },
            {
              n_nationkey: 14,
              n_name: "KENYA                    ",
              n_regionkey: 0,
              n_comment:
                " pending excuses haggle furiously deposits. pending, express pinto beans wake fluffily past t",
              r_regionkey: 0,
              r_name: "AFRICA                   ",
              r_comment:
                "lar deposits. blithely final packages cajole. regular waters are final requests. regular accounts are according to ",
            },
            {
              n_nationkey: 13,
              n_name: "JORDAN                   ",
              n_regionkey: 4,
              n_comment:
                "ic deposits are blithely about the carefully regular pa",
              r_regionkey: 4,
              r_name: "MIDDLE EAST              ",
              r_comment:
                "uickly special accounts cajole carefully blithely close requests. carefully final asymptotes haggle furiousl",
            },
            {
              n_nationkey: 1,
              n_name: "ARGENTINA                ",
              n_regionkey: 1,
              n_comment:
                "al foxes promise slyly according to the regular accounts. bold requests alon",
              r_regionkey: 1,
              r_name: "AMERICA                  ",
              r_comment: "hs use ironic, even requests. s",
            },
            {
              n_nationkey: 9,
              n_name: "INDONESIA                ",
              n_regionkey: 2,
              n_comment:
                " slyly express asymptotes. regular deposits haggle slyly. carefully ironic hockey players sleep blithely. carefull",
              r_regionkey: 2,
              r_name: "ASIA                     ",
              r_comment: "ges. thinly even pinto beans ca",
            },
            {
              n_nationkey: 0,
              n_name: "ALGERIA                  ",
              n_regionkey: 0,
              n_comment: " haggle. carefully final deposits detect slyly agai",
              r_regionkey: 0,
              r_name: "AFRICA                   ",
              r_comment:
                "lar deposits. blithely final packages cajole. regular waters are final requests. regular accounts are according to ",
            },
            {
              n_nationkey: 4,
              n_name: "EGYPT                    ",
              n_regionkey: 4,
              n_comment:
                "y above the carefully unusual theodolites. final dugouts are quickly across the furiously regular d",
              r_regionkey: 4,
              r_name: "MIDDLE EAST              ",
              r_comment:
                "uickly special accounts cajole carefully blithely close requests. carefully final asymptotes haggle furiousl",
            },
            {
              n_nationkey: 12,
              n_name: "JAPAN                    ",
              n_regionkey: 2,
              n_comment: "ously. final, express gifts cajole a",
              r_regionkey: 2,
              r_name: "ASIA",
              r_comment: "ges. thinly even pinto beans ca",
            },
          ],
        },
        "public.customer_orders_lineitem_denormalized": {
          attributes: [
            "l_orderkey",
            "l_partkey",
            "l_suppkey",
            "l_linenumber",
            "l_quantity",
            "l_extendedprice",
            "l_discount",
            "l_tax",
            "l_returnflag",
            "l_linestatus",
            "l_shipdate",
            "l_commitdate",
            "l_receiptdate",
            "l_shipinstruct",
            "l_shipmode",
            "l_comment",
            "o_orderkey",
            "o_custkey",
            "o_orderstatus",
            "o_totalprice",
            "o_orderdate",
            "o_orderpriority",
            "o_clerk",
            "o_shippriority",
            "o_comment",
            "c_custkey",
            "c_name",
            "c_address",
            "c_nationkey",
            "c_phone",
            "c_acctbal",
            "c_mktsegment",
            "c_comment",
          ],
          rows: [
            {
              l_orderkey: 2086,
              l_partkey: 60,
              l_suppkey: 1,
              l_linenumber: 1,
              l_quantity: "22.00",
              l_extendedprice: "21121.32",
              l_discount: "0.03",
              l_tax: "0.07",
              l_returnflag: "R",
              l_linestatus: "F",
              l_shipdate: "1994-12-03T23:00:00.000Z",
              l_commitdate: "1994-12-15T23:00:00.000Z",
              l_receiptdate: "1994-12-19T23:00:00.000Z",
              l_shipinstruct: "DELIVER IN PERSON        ",
              l_shipmode: "RAIL      ",
              l_comment: "idly busy acc",
              o_orderkey: 2086,
              o_custkey: 142,
              o_orderstatus: "F",
              o_totalprice: "188985.18",
              o_orderdate: "1994-10-18T23:00:00.000Z",
              o_orderpriority: "1-URGENT       ",
              o_clerk: "Clerk#000000046",
              o_shippriority: 0,
              o_comment: " permanently regular",
              c_custkey: 142,
              c_name: "Customer#000000142",
              c_address: "AnJ5lxtLjioClr2khl9pb8NLxG2,",
              c_nationkey: 9,
              c_phone: "19-407-425-2584",
              c_acctbal: "2209.81",
              c_mktsegment: "AUTOMOBILE",
              c_comment: ". even, express theodolites upo",
            },
            {
              l_orderkey: 775,
              l_partkey: 108,
              l_suppkey: 5,
              l_linenumber: 3,
              l_quantity: "20.00",
              l_extendedprice: "20162.00",
              l_discount: "0.01",
              l_tax: "0.08",
              l_returnflag: "N",
              l_linestatus: "F",
              l_shipdate: "1995-06-16T22:00:00.000Z",
              l_commitdate: "1995-05-21T22:00:00.000Z",
              l_receiptdate: "1995-07-12T22:00:00.000Z",
              l_shipinstruct: "COLLECT COD              ",
              l_shipmode: "AIR       ",
              l_comment: "en dependencies nag slowly ",
              o_orderkey: 775,
              o_custkey: 134,
              o_orderstatus: "F",
              o_totalprice: "59455.61",
              o_orderdate: "1995-03-17T23:00:00.000Z",
              o_orderpriority: "1-URGENT       ",
              o_clerk: "Clerk#000000191",
              o_shippriority: 0,
              o_comment:
                "kly express requests. fluffily silent accounts poach furiously",
              c_custkey: 134,
              c_name: "Customer#000000134",
              c_address: "sUiZ78QCkTQPICKpA9OBzkUp2FM",
              c_nationkey: 11,
              c_phone: "21-200-159-5932",
              c_acctbal: "4608.90",
              c_mktsegment: "BUILDING  ",
              c_comment: "yly fluffy foxes boost final ideas. b",
            },
            {
              l_orderkey: 2883,
              l_partkey: 195,
              l_suppkey: 8,
              l_linenumber: 5,
              l_quantity: "36.00",
              l_extendedprice: "39426.84",
              l_discount: "0.07",
              l_tax: "0.06",
              l_returnflag: "A",
              l_linestatus: "F",
              l_shipdate: "1995-05-01T22:00:00.000Z",
              l_commitdate: "1995-03-13T23:00:00.000Z",
              l_receiptdate: "1995-05-29T22:00:00.000Z",
              l_shipinstruct: "COLLECT COD              ",
              l_shipmode: "MAIL      ",
              l_comment: "ests detect slyly special packages",
              o_orderkey: 2883,
              o_custkey: 121,
              o_orderstatus: "F",
              o_totalprice: "170360.27",
              o_orderdate: "1995-01-22T23:00:00.000Z",
              o_orderpriority: "5-LOW          ",
              o_clerk: "Clerk#000000180",
              o_shippriority: 0,
              o_comment: "uses. carefully ironic accounts lose fluffil",
              c_custkey: 121,
              c_name: "Customer#000000121",
              c_address: "tv nCR2YKupGN73mQudO",
              c_nationkey: 17,
              c_phone: "27-411-990-2959",
              c_acctbal: "6428.32",
              c_mktsegment: "BUILDING  ",
              c_comment:
                "uriously stealthy ideas. carefully final courts use carefully",
            },
            {
              l_orderkey: 4135,
              l_partkey: 2,
              l_suppkey: 3,
              l_linenumber: 1,
              l_quantity: "23.00",
              l_extendedprice: "20746.00",
              l_discount: "0.06",
              l_tax: "0.01",
              l_returnflag: "N",
              l_linestatus: "O",
              l_shipdate: "1997-04-08T22:00:00.000Z",
              l_commitdate: "1997-05-11T22:00:00.000Z",
              l_receiptdate: "1997-04-15T22:00:00.000Z",
              l_shipinstruct: "TAKE BACK RETURN         ",
              l_shipmode: "FOB       ",
              l_comment: "posits cajole furiously carefully",
              o_orderkey: 4135,
              o_custkey: 37,
              o_orderstatus: "O",
              o_totalprice: "99577.55",
              o_orderdate: "1997-03-09T23:00:00.000Z",
              o_orderpriority: "3-MEDIUM       ",
              o_clerk: "Clerk#000000627",
              o_shippriority: 0,
              o_comment: "ly quietly even ideas. deposits haggle blithely",
              c_custkey: 37,
              c_name: "Customer#000000037",
              c_address: "7EV4Pwh,3SboctTWt",
              c_nationkey: 8,
              c_phone: "18-385-235-7162",
              c_acctbal: "-917.75",
              c_mktsegment: "FURNITURE ",
              c_comment:
                "ilent packages are carefully among the deposits. furiousl",
            },
            {
              l_orderkey: 101,
              l_partkey: 164,
              l_suppkey: 9,
              l_linenumber: 2,
              l_quantity: "36.00",
              l_extendedprice: "38309.76",
              l_discount: "0.00",
              l_tax: "0.01",
              l_returnflag: "N",
              l_linestatus: "O",
              l_shipdate: "1996-05-18T22:00:00.000Z",
              l_commitdate: "1996-04-30T22:00:00.000Z",
              l_receiptdate: "1996-06-03T22:00:00.000Z",
              l_shipinstruct: "DELIVER IN PERSON        ",
              l_shipmode: "AIR       ",
              l_comment: "tes. blithely pending dolphins x-ray f",
              o_orderkey: 101,
              o_custkey: 28,
              o_orderstatus: "O",
              o_totalprice: "95591.40",
              o_orderdate: "1996-03-16T23:00:00.000Z",
              o_orderpriority: "3-MEDIUM       ",
              o_clerk: "Clerk#000000419",
              o_shippriority: 0,
              o_comment: "ding accounts above the slyly final asymptote",
              c_custkey: 28,
              c_name: "Customer#000000028",
              c_address: "iVyg0daQ,Tha8x2WPWA9m2529m",
              c_nationkey: 8,
              c_phone: "18-774-241-1462",
              c_acctbal: "1007.18",
              c_mktsegment: "FURNITURE ",
              c_comment: " along the regular deposits. furiously final pac",
            },
            {
              l_orderkey: 4803,
              l_partkey: 189,
              l_suppkey: 10,
              l_linenumber: 5,
              l_quantity: "21.00",
              l_extendedprice: "22872.78",
              l_discount: "0.03",
              l_tax: "0.06",
              l_returnflag: "N",
              l_linestatus: "O",
              l_shipdate: "1996-05-24T22:00:00.000Z",
              l_commitdate: "1996-03-14T23:00:00.000Z",
              l_receiptdate: "1996-06-08T22:00:00.000Z",
              l_shipinstruct: "COLLECT COD              ",
              l_shipmode: "FOB       ",
              l_comment: " silent packages use. b",
              o_orderkey: 4803,
              o_custkey: 124,
              o_orderstatus: "O",
              o_totalprice: "158776.68",
              o_orderdate: "1996-02-07T23:00:00.000Z",
              o_orderpriority: "5-LOW          ",
              o_clerk: "Clerk#000000892",
              o_shippriority: 0,
              o_comment: "lly unusual courts are ironic",
              c_custkey: 124,
              c_name: "Customer#000000124",
              c_address: "aTbyVAW5tCd,v09O",
              c_nationkey: 18,
              c_phone: "28-183-750-7809",
              c_acctbal: "1842.49",
              c_mktsegment: "AUTOMOBILE",
              c_comment: "le fluffily even dependencies. quietly s",
            },
            {
              l_orderkey: 481,
              l_partkey: 21,
              l_suppkey: 2,
              l_linenumber: 2,
              l_quantity: "19.00",
              l_extendedprice: "17499.38",
              l_discount: "0.08",
              l_tax: "0.01",
              l_returnflag: "R",
              l_linestatus: "F",
              l_shipdate: "1993-01-08T23:00:00.000Z",
              l_commitdate: "1992-11-26T23:00:00.000Z",
              l_receiptdate: "1993-01-13T23:00:00.000Z",
              l_shipinstruct: "TAKE BACK RETURN         ",
              l_shipmode: "AIR       ",
              l_comment: "p blithely after t",
              o_orderkey: 481,
              o_custkey: 31,
              o_orderstatus: "F",
              o_totalprice: "117827.18",
              o_orderdate: "1992-10-07T23:00:00.000Z",
              o_orderpriority: "2-HIGH         ",
              o_clerk: "Clerk#000000230",
              o_shippriority: 0,
              o_comment: "ly final ideas. packages haggle fluffily",
              c_custkey: 31,
              c_name: "Customer#000000031",
              c_address: "LUACbO0viaAv6eXOAebryDB xjVst",
              c_nationkey: 23,
              c_phone: "33-197-837-7094",
              c_acctbal: "5236.89",
              c_mktsegment: "HOUSEHOLD ",
              c_comment: "s use among the blithely pending depo",
            },
            {
              l_orderkey: 3554,
              l_partkey: 175,
              l_suppkey: 5,
              l_linenumber: 1,
              l_quantity: "32.00",
              l_extendedprice: "34405.44",
              l_discount: "0.01",
              l_tax: "0.05",
              l_returnflag: "N",
              l_linestatus: "O",
              l_shipdate: "1995-09-27T23:00:00.000Z",
              l_commitdate: "1995-08-31T22:00:00.000Z",
              l_receiptdate: "1995-10-06T23:00:00.000Z",
              l_shipinstruct: "NONE                     ",
              l_shipmode: "RAIL      ",
              l_comment: ". blithely ironic t",
              o_orderkey: 3554,
              o_custkey: 44,
              o_orderstatus: "O",
              o_totalprice: "98335.61",
              o_orderdate: "1995-06-16T22:00:00.000Z",
              o_orderpriority: "5-LOW          ",
              o_clerk: "Clerk#000000931",
              o_shippriority: 0,
              o_comment: "hely ironic requests haggl",
              c_custkey: 44,
              c_name: "Customer#000000044",
              c_address: "Oi,dOSPwDu4jo4x,,P85E0dmhZGvNtBwi",
              c_nationkey: 16,
              c_phone: "26-190-260-5375",
              c_acctbal: "7315.94",
              c_mktsegment: "AUTOMOBILE",
              c_comment: "r requests around the unusual, bold a",
            },
            {
              l_orderkey: 4230,
              l_partkey: 75,
              l_suppkey: 6,
              l_linenumber: 4,
              l_quantity: "28.00",
              l_extendedprice: "27301.96",
              l_discount: "0.01",
              l_tax: "0.03",
              l_returnflag: "R",
              l_linestatus: "F",
              l_shipdate: "1992-05-11T22:00:00.000Z",
              l_commitdate: "1992-05-09T22:00:00.000Z",
              l_receiptdate: "1992-05-31T22:00:00.000Z",
              l_shipinstruct: "TAKE BACK RETURN         ",
              l_shipmode: "MAIL      ",
              l_comment: "nt instruct",
              o_orderkey: 4230,
              o_custkey: 140,
              o_orderstatus: "F",
              o_totalprice: "219709.60",
              o_orderdate: "1992-03-03T23:00:00.000Z",
              o_orderpriority: "1-URGENT       ",
              o_clerk: "Clerk#000000364",
              o_shippriority: 0,
              o_comment: "lly ironic deposits integrate carefully about the fu",
              c_custkey: 140,
              c_name: "Customer#000000140",
              c_address: "XRqEPiKgcETII,iOLDZp5jA",
              c_nationkey: 4,
              c_phone: "14-273-885-6505",
              c_acctbal: "9963.15",
              c_mktsegment: "MACHINERY ",
              c_comment:
                "ies detect slyly ironic accounts. slyly ironic theodolites hag",
            },
            {
              l_orderkey: 3271,
              l_partkey: 95,
              l_suppkey: 6,
              l_linenumber: 3,
              l_quantity: "14.00",
              l_extendedprice: "13931.26",
              l_discount: "0.05",
              l_tax: "0.01",
              l_returnflag: "A",
              l_linestatus: "F",
              l_shipdate: "1992-02-23T23:00:00.000Z",
              l_commitdate: "1992-02-13T23:00:00.000Z",
              l_receiptdate: "1992-03-22T23:00:00.000Z",
              l_shipinstruct: "NONE                     ",
              l_shipmode: "AIR       ",
              l_comment: "ending, even packa",
              o_orderkey: 3271,
              o_custkey: 34,
              o_orderstatus: "F",
              o_totalprice: "86534.05",
              o_orderdate: "1991-12-31T23:00:00.000Z",
              o_orderpriority: "1-URGENT       ",
              o_clerk: "Clerk#000000421",
              o_shippriority: 0,
              o_comment: "s. furiously regular requests",
              c_custkey: 34,
              c_name: "Customer#000000034",
              c_address: "Q6G9wZ6dnczmtOx509xgE,M2KV",
              c_nationkey: 15,
              c_phone: "25-344-968-5422",
              c_acctbal: "8589.70",
              c_mktsegment: "HOUSEHOLD ",
              c_comment: "nder against the even, pending accounts. even",
            },
          ],
        },
      };
      res.json(result);
    } catch (error) {
      console.error(error);
      res.status(502).json({ error: "Could not get tables" });
    }
  }

  return getTableHead;
}
